##This funcion loads training and test data and merge
##them together to form a new table. The new table has
## two new columns, one for the activity and another
## to identify the subject. Tidy data is generated by
## summarizing the new table.

##load dplyr packacge
library(dplyr)
##Create a funtcion that labels the activities
FlabelActiv <- function (x){
        if (x == 1){
                return ("WALKING")
        }
        if (x == 2){
                return ("WALKING_UPSTAIRS")
        }
        if (x == 3){
                return ("WALKING_DOWNSTAIRS")
        }
        if (x == 4){
                return ("SITTING")
        }
        if (x == 5){
                return ("STANDING")
        }
        if (x == 6){
                return ("LAYING")
        }

}


## Read test data
test_table<-read.table("./test/X_test.txt")
##Read train data
train_table<-read.table("./train/X_train.txt")
##Merges the two data sets
merged_table=merge(test_table,train_table)

##Read the activity label for training data
activ_train<-read.table("./train/y_train.txt")
##Unlist the activ_train data to allow loop function mapply
activ_train<-unlist(activ_train)
##Apply the Labels
activ_train<-sapply(activ_train,FlabelActiv)
##Inserts Activity Labels in the Table
train_table<-mutate(train_table,Activity=activ_train)
#Read the subject labels for training data
subject_train<-read.table("./train/subject_train.txt")
#Unlist Subject 
subject_train<-unlist(subject_train)
##Adds subject train to the train table
train_table<-mutate(train_table,Subject=subject_train)



##Read the activity label for testing data
activ_test<-read.table("./test/y_test.txt")
##Unlist the activ_train data to allow loop function mapply
activ_test<-unlist(activ_test)
##Apply the Labels
activ_test<-sapply(activ_test,FlabelActiv)
##Inserts Activity Labels in the Table
test_table<-mutate(test_table,Activity=activ_test)
#Read the subject labels for training data
subject_test<-read.table("./test/subject_test.txt")
#Unlist Subject 
subject_test<-unlist(subject_test)
##Adds subject train to the test table
test_table<-mutate(test_table,Subject=subject_test)

##Merge the two tables
merged_table<-merge(test_table,train_table,all=TRUE)

##Divide table by groups pf activities and subject
merged_table_by_activ_by_sub<-group_by(merged_table,Activity,Subject)

##Summarize divied table showing the mean of each variable
tidy_data<-summarize_each(merged_table_by_activ_by_sub,funs(mean))

##Write table to archive
write.table(tidy_data,file="./tidy_data.txt",row.names = FALSE)

